export default {

  en: new Map(Object.entries({
    Backquote: { lower: '`', upper: '~' },
    Digit1: { lower: '1', upper: '!' },
    Digit2: { lower: '2', upper: '@' },
    Digit3: { lower: '3', upper: '#' },
    Digit4: { lower: '4', upper: '$' },
    Digit5: { lower: '5', upper: '%' },
    Digit6: { lower: '6', upper: '^' },
    Digit7: { lower: '7', upper: '&' },
    Digit8: { lower: '8', upper: '*' },
    Digit9: { lower: '9', upper: '(' },
    Digit0: { lower: '0', upper: ')' },
    Minus: { lower: '-', upper: '_' },
    Equal: { lower: '=', upper: '+' },
    Tab: { lower: '\t', upper: '\t' },
    KeyQ: { lower: 'q', upper: 'Q' },
    KeyW: { lower: 'w', upper: 'W' },
    KeyE: { lower: 'e', upper: 'E' },
    KeyR: { lower: 'r', upper: 'R' },
    KeyT: { lower: 't', upper: 'T' },
    KeyY: { lower: 'y', upper: 'Y' },
    KeyU: { lower: 'u', upper: 'U' },
    KeyI: { lower: 'i', upper: 'I' },
    KeyO: { lower: 'o', upper: 'O' },
    KeyP: { lower: 'p', upper: 'P' },
    BracketLeft: { lower: '[', upper: '{' },
    BracketRight: { lower: ']', upper: '}' },
    Backslash: { lower: '\\', upper: '|' },
    KeyA: { lower: 'a', upper: 'A' },
    KeyS: { lower: 's', upper: 'S' },
    KeyD: { lower: 'd', upper: 'D' },
    KeyF: { lower: 'f', upper: 'F' },
    KeyG: { lower: 'g', upper: 'G' },
    KeyH: { lower: 'h', upper: 'H' },
    KeyJ: { lower: 'j', upper: 'J' },
    KeyK: { lower: 'k', upper: 'K' },
    KeyL: { lower: 'l', upper: 'L' },
    Semicolon: { lower: ';', upper: ':' },
    Quote: { lower: '\'', upper: '"' },
    Enter: { lower: '\n', upper: '\n' },
    KeyZ: { lower: 'z', upper: 'Z' },
    KeyX: { lower: 'x', upper: 'X' },
    KeyC: { lower: 'c', upper: 'C' },
    KeyV: { lower: 'v', upper: 'V' },
    KeyB: { lower: 'b', upper: 'B' },
    KeyN: { lower: 'n', upper: 'N' },
    KeyM: { lower: 'm', upper: 'M' },
    Comma: { lower: ',', upper: '<' },
    Period: { lower: '.', upper: '>' },
    Slash: { lower: '/', upper: '?' },
    ArrowUp: { lower: '▲', upper: '▲' },
    Space: { lower: ' ', upper: ' ' },
    ArrowLeft: { lower: '◄', upper: '◄' },
    ArrowDown: { lower: '▼', upper: '▼' },
    ArrowRight: { lower: '►', upper: '►' },
  })),

  ru: new Map(Object.entries({
    Backquote: { lower: 'ё', upper: 'Ё' },
    Digit1: { lower: '1', upper: '!' },
    Digit2: { lower: '2', upper: '"' },
    Digit3: { lower: '3', upper: '№' },
    Digit4: { lower: '4', upper: ';' },
    Digit5: { lower: '5', upper: '%' },
    Digit6: { lower: '6', upper: ':' },
    Digit7: { lower: '7', upper: '?' },
    Digit8: { lower: '8', upper: '*' },
    Digit9: { lower: '9', upper: '(' },
    Digit0: { lower: '0', upper: ')' },
    Minus: { lower: '-', upper: '_' },
    Equal: { lower: '=', upper: '+' },
    Tab: { lower: '\t', upper: '\t' },
    KeyQ: { lower: 'й', upper: 'Й' },
    KeyW: { lower: 'ц', upper: 'Ц' },
    KeyE: { lower: 'у', upper: 'У' },
    KeyR: { lower: 'к', upper: 'К' },
    KeyT: { lower: 'е', upper: 'Е' },
    KeyY: { lower: 'н', upper: 'Н' },
    KeyU: { lower: 'г', upper: 'Г' },
    KeyI: { lower: 'ш', upper: 'Ш' },
    KeyO: { lower: 'щ', upper: 'Щ' },
    KeyP: { lower: 'з', upper: 'З' },
    BracketLeft: { lower: 'х', upper: 'Х' },
    BracketRight: { lower: 'ъ', upper: 'Ъ' },
    Backslash: { lower: '\\', upper: '/' },
    KeyA: { lower: 'ф', upper: 'Ф' },
    KeyS: { lower: 'ы', upper: 'Ы' },
    KeyD: { lower: 'в', upper: 'В' },
    KeyF: { lower: 'а', upper: 'А' },
    KeyG: { lower: 'п', upper: 'П' },
    KeyH: { lower: 'р', upper: 'Р' },
    KeyJ: { lower: 'о', upper: 'О' },
    KeyK: { lower: 'л', upper: 'Л' },
    KeyL: { lower: 'д', upper: 'Д' },
    Semicolon: { lower: 'ж', upper: 'Ж' },
    Quote: { lower: 'э', upper: 'Э' },
    Enter: { lower: '\n', upper: '\n', breakRow: true },
    KeyZ: { lower: 'я', upper: 'Я' },
    KeyX: { lower: 'ч', upper: 'Ч' },
    KeyC: { lower: 'с', upper: 'С' },
    KeyV: { lower: 'м', upper: 'М' },
    KeyB: { lower: 'и', upper: 'И' },
    KeyN: { lower: 'т', upper: 'Т' },
    KeyM: { lower: 'ь', upper: 'Ь' },
    Comma: { lower: 'б', upper: 'Б' },
    Period: { lower: 'ю', upper: 'Ю' },
    Slash: { lower: '.', upper: ',' },
    ArrowUp: { lower: '▲', upper: '▲' },
    Space: { lower: ' ', upper: ' ' },
    ArrowLeft: { lower: '◄', upper: '◄' },
    ArrowDown: { lower: '▼', upper: '▼' },
    ArrowRight: { lower: '►', upper: '►' },
  })),

  sys: new Map(Object.entries({
    Backspace: { pos: 14, label: 'Backspace', breakRow: true },
    Delete: { pos: 29, label: 'Delete', breakRow: true },
    CapsLock: { pos: 30, label: 'Caps Lock' },
    ShiftLeft: { pos: 43, label: 'Shift' },
    ShiftRight: { pos: 55, label: 'Shift', breakRow: true },
    ControlLeft: { pos: 56, label: 'Ctrl' },
    /* MetaLeft: 57, */
    AltLeft: { pos: 57, label: 'Alt' },
    AltRight: { pos: 59, label: 'Alt' },
    ControlRight: { pos: 63, label: 'Ctrl' },
  })),

};
